### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by arabesc** [ruuk/plugin.image.flickr#7]
Windows 10 Fall Creators Update / Kodi v17.6 "Krypton"
Plugin doesn't work
```
03:50:43.049 T:6856  NOTICE: plugin.image.flickr: Version: 1.1.1
03:50:43.049 T:6856  NOTICE: plugin.image.flickr: Encoding: cp1251
03:50:43.050 T:6856  NOTICE: plugin.image.flickr: Could not import ShareSocial
...
03:50:46.905 T:440   ERROR: Previous line repeats 3 times.
03:50:46.906 T:440  NOTICE: plugin.image.flickr: UNHANDLED ERROR
03:50:46.906 T:440   ERROR: Traceback (most recent call last):
03:50:46.906 T:440   ERROR:   File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.image.flickr\default.py", line 820, in doPlugin
03:50:46.906 T:440   ERROR:     fsession.INTERESTING(page)
03:50:46.906 T:440   ERROR:   File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.image.flickr\default.py", line 687, in INTERESTING
03:50:46.906 T:440   ERROR:     self.addPhotos(self.flickr.interestingness_getList,11,page=page)
03:50:46.906 T:440   ERROR:   File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.image.flickr\default.py", line 447, in addPhotos
03:50:46.906 T:440   ERROR:     for photo in self.flickr.walk_photos_by_page(method,page=page,per_page=mpp,extras=extras,**kwargs):
03:50:46.906 T:440   ERROR:   File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.image.flickr\default.py", line 117, in walk_photos_by_page
03:50:46.906 T:440   ERROR:     rsp = method(**params)
03:50:46.906 T:440   ERROR:   File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.image.flickr\flickrapi\__init__.py", line 338, in handler
03:50:46.906 T:440   ERROR:     'oauth_token': self.token_cache.token[0]
03:50:46.906 T:440   ERROR: TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ruuk** [comment]
Have you tried reauthorizing from the option in the add-on's settings?
